[workspace]
resolver = "3"
members = [
    "crates/lantern-teleport-core",
    "crates/lantern-teleport-cli",
    "crates/lantern-teleport-tui",
]

[workspace.package]
version = "0.1.2"
edition = "2024"
license = "MIT"
authors = ["lantern-teleport contributors"]
