[package]
name = "lantern-teleport-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Core library for lantern teleport functionality"

[dependencies]
